console.log("javascript basic practice")

let a = 5
let b = "5"

console.log(a==b)//15
console.log(a===b)//-5
console.log(a!==b)//50
console.log(a>=b)//1.2
console.log(a%b)//0.5
console.log(++b)//11
console.log(--b)//9



const x = 2
const y = 4

console.log(x)
console.log(y)

let age = 22
console.log(age)
console.log("choudhary")

let miteshis22 = true
console.log(miteshis22)

let mitesh = null
console.log(mitesh)

let college = {
    name :"mitesh",
    age:22,
    class :"MCA"
}

let college2 = {
    name :"avish",
    age:18,
    class :"+2"
}
let college3 = {
    name :"vasu",
    age:16,
    class :"10th"
}

let university = {
    first: college,
    second:college2,
    thired:college3
}

console.log(college)
console.log(college2)
console.log(college3)
console.log(university)

let iseven = 10 * 2 === 20 ? "no is even" : "no is odd"
console.log(iseven)

    